### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by AaronPatterson1** [accountability-tracker/habit_tracker#15]
![image](https://user-images.githubusercontent.com/22058050/209882658-f05f05f9-8a6c-4263-8dde-5606e255764b.png)
![image](https://user-images.githubusercontent.com/22058050/209882926-9e8a4893-73aa-491e-bc2c-856221b23db7.png)
![image](https://user-images.githubusercontent.com/22058050/209883095-fd0acd5e-0181-4c93-b016-36297efbb265.png)
![image](https://user-images.githubusercontent.com/22058050/209883121-85667f7b-233d-4c24-b986-443c9ac8f0d8.png)
![image](https://user-images.githubusercontent.com/22058050/209883155-8d70e122-b481-4165-ba3e-a9e98d6d5852.png)

**Comment by clearfeld** [comment]
New UX screenshots

![Screenshot_2023-06-01-12-56-19-33_28856ae86989c6de86f11be809868565](https://github.com/accountability-tracker/habit_tracker/assets/49600278/cc9e5a26-99d5-4c20-acd0-fe3d42724865)
![Screenshot_2023-06-01-12-56-22-77_28856ae86989c6de86f11be809868565](https://github.com/accountability-tracker/habit_tracker/assets/49600278/7ac6e9b8-b0ea-4e21-9c3f-cc4fc4dd14e5)
![Screenshot_2023-06-01-12-56-17-02_28856ae86989c6de86f11be809868565](https://github.com/accountability-tracker/habit_tracker/assets/49600278/cb58298c-01fc-416d-bbd3-aeb8cca09782)
![Screenshot_2023-06-01-12-56-30-01_28856ae86989c6de86f11be809868565](https://github.com/accountability-tracker/habit_tracker/assets/49600278/b5d4555b-0db2-4207-a063-4621181e6e17)
